### ISSUE TITLE
Relationships tab margins messed up

### ISSUE THREAD

**Issue by mattwire** [civicrm/org.civicrm.shoreditch#295]
This can be fixed by removing scss/civicrm/managers/_manager.scss
Is this an accidental carryover from CiviHR?

![relationshiptab](https://user-images.githubusercontent.com/2052161/45435416-721c0500-b6a8-11e8-974c-0b1b678bff64.png)

**Comment by mattwire** [comment]
ping @AkA84

**Comment by mattwire** [comment]
@mukeshcompucorp Could you review this?

**Comment by AkA84** [comment]
@mattwire I can't seem to replicate the issue

<img width="1439" alt="error" src="https://user-images.githubusercontent.com/6400898/45473421-4eec6680-b737-11e8-91f1-1e9da9327ff9.png">

this on chrome/firefox, seven theme, shoreditch v0.1-alpha24

**Comment by mattwire** [comment]
@AkA84 Can you test with a drupal bootstrap theme? (eg. the bootstrap base theme: https://www.drupal.org/project/bootstrap). Then you will see the problem.

**Comment by mattwire** [comment]
Related to this issue: https://github.com/civicrm/civicrm-core/pull/12800

**Comment by AkA84** [comment]
@mattwire Shoreditch currently only supports the Seven theme, please see here https://github.com/civicrm/org.civicrm.shoreditch/#supported-cmss

> At the moment the theme is being developed to work only in Drupal (with default theme set to "Seven")

We'd be happy to review and merge a PR with a fix for this particular drupal theme, but at the moment internally we are focusing on the support of Seven only

**Comment by mattwire** [comment]
@AkA84 I think we just need to remove the file `scss/civicrm/managers/_manager.scss`

But since a few days I can't build latest master so cannot test with seven theme:

```
Error in plugin "sass"
Message:
    scss/bootstrap/bootstrap.scss
Error: File to import not found or unreadable: SCSSROOT/org.civicrm.shoreditch/scss/angular/vendor/ALL.
        on line 1 of scss/bootstrap/bootstrap.scss
>> @import 'SCSSROOT/org.civicrm.shoreditch/scss/angular/vendor/ALL';

   ^

[12:43:46] Finished 'buildBootstrapCSS' after 56 ms
[12:43:46] Finished 'sass:bootstrap' after 1.22 s
Error in plugin "sass"
Message:
    scss/civicrm/custom-civicrm.scss
Error: File to import not found or unreadable: SCSSROOT/org.civicrm.shoreditch/scss/bootstrap/overrides/variables.
        on line 4 of scss/civicrm/custom-civicrm.scss
>> @import 'SCSSROOT/org.civicrm.shoreditch/scss/bootstrap/overrides/variables'
```

**Comment by AkA84** [comment]
@mattwire I don't think we can simply get rid of an entire partial that provides the style for an whole tab; whatever solution will address the issue on that particular theme, it should be build on top of the style provided that `_manager.scss`

Re that error, the theme uses https://github.com/totten/civicrm-scssroot#v0.1.1 in its gulp task, please make sure that your dev env meets the [requirements](https://github.com/totten/civicrm-scssroot#requirements)

**Comment by mattwire** [comment]
@aka84 have you looked at the contents of _manager.scss? As it is not providing the style for a whole tab at all - but a number of overrides and exceptions (including !important which is generally bad practise and makes it extremely hard to override with custom CSS on top).
The file which provides style for the whole tab is in contact/pages/_relationships.scss

My dev env is correct per requirements and worked until a few days ago when I updated Shoreditch master. I have been reviewing PRs that your colleagues have submitted to civicrm core and I had hoped that you might spend a little more time in return looking at this issue for me - it seems from your comments that you didn't even look at the contents of _managers.scss

**Comment by AkA84** [comment]
@mattwire I did look at the content of the file and also tried to remove it as soon as you suggested it, this is the result:

![no-file](https://user-images.githubusercontent.com/6400898/45680381-14ba0500-bb3b-11e8-939d-dddfed4419be.png)

_(Please note that while the screenshot is for CiviCRM v5.4.0 I also tested it on CiviCRM v5.5.1)_

As expected the style of the tab's content doesn't look right anymore. My wording was incorrect, as the partial does not provide the full style for the tab, but it does provide styles that are applied to different parts of it (heading, pager, etc)

I also pulled the content of [your PR](https://github.com/civicrm/civicrm-core/pull/12800) and tested the theme again without that partial

![w-patch](https://user-images.githubusercontent.com/6400898/45682438-8fd1ea00-bb40-11e8-9cc5-0e3fd7c04f0e.png)

It is an improvement but as you can see there are still bits that do not look right

So from what I can see we can't simply remove the partial: if that works for your specific site then by all means, but any solution that is to be merged in the original repo needs to not only work for the theme you are using, but also ensure that it doesn't introduce regression issues with the officially supported theme (Seven)

As I said we currently officially support only Seven, as we are focusing our time and resources to make Shoreditch look right on it first and foremost. But if you submit a PR we'd gladly use part of that time and resources to review it and test it, as long as it meets the criteria I wrote above.

Btw I tried to use https://www.drupal.org/project/bootstrap as you suggested, and this is what i get:

![bootstrap-theme](https://user-images.githubusercontent.com/6400898/45680379-14ba0500-bb3b-11e8-9d63-cc7794d260ab.png)


About your gulp task issue, I find it hard to troubleshoot it because I can't replicate it, have you tried `git bisect` to try to pinpoint the commit that introduced the problem for you?

**Comment by mattwire** [comment]
Closing as I no longer use this CiviCRM theme due to it's incompatibility with drupal bootstrap.  Instead I use https://github.com/mattwire/civicrm-haystacktheme
