### ISSUE TITLE
wordpress?

### ISSUE THREAD

**Issue by caliginous** [civicrm/org.civicrm.shoreditch#350]
has anyone got this working in wordpress in production?

**Comment by themak1985** [comment]
@caliginous It works with wordpress - but I would not recommend it at this time due to the developers really only focusing on Drupal (not that they don't want to support other CMS's - just only so much capacity).  CiviCRM Admin Utilities is able to restrict a bunch of the shoreditch stylesheets from loading on public pages - which helps - but most of us in the Wordpress CiviCRM world have adopted [CiviCRM Admin Utilities Admin Styling](https://wordpress.org/plugins/civicrm-admin-utilities/) - which makes CiviCRM adopt most of Wordpress styling - so it looks like any other wordpress plugin.

**Comment by caliginous** [comment]
Thanks, I will look into that.
