### ISSUE TITLE
 php 7.4 - curly braces is deprecated

### ISSUE THREAD

**Issue by Rar9** [civicrm/org.civicrm.shoreditch#521]
drupal 9.1.10 with php 7.4.x

when cv en org.civicrm.shoreditch

I get 
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/vhosts/drupal/web/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gdpr/gdpr.civix.php on line 246

**Comment by MegaphoneJon** [comment]
You didn't mention your Shoreditch version, but it must not be the latest version.  This was fixed in an April 8th commit, so you can solve this via an upgrade.

The code that needs updating is auto-generated by `civix`, the tool that generates the "skeleton" of a CiviCRM extension.  `civix` has been updated to generate non-deprecated code, but I've had to update over a hundred extensions with the updated code, so you should expect to see this problem again.

**Comment by Rar9** [comment]
I do git pull from time to time.

Will try civix generate:module 
-- 
Mit freundlichen Grüßen /with best regards,

Robert Krölls
Am Sonnenhof 16
47800 Krefeld

Am 11. Juni 2021 16:16:38 MESZ schrieb Jon ***@***.***>:

**Comment by deb1990** [comment]
@Rar9 Also if you see the error
> /var/www/vhosts/drupal/web/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gdpr/gdpr.civix.php

The error is in `uk.co.vedaconsulting.gdpr` repo, and not in shoreditch.
